<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>bench</AssemblyName>
    <RootNamespace>bench</RootNamespace>
    <StartupObject>SCC.Program</StartupObject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="benchmark.cs" />
    <Compile Include="staging/**/*.cs" />
    <Compile Include="../../bench_utils/csharp/Bench.cs" />
  </ItemGroup>

</Project>
